version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: adminportfolio
      POSTGRES_PASSWORD: kX*AzSH^j5k!z8W69Y%Qaa0$C
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 portfolio.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - webnet

volumes:
  postgres_data:

networks:
  webnet: