# Generated by Django 5.1 on 2024-08-08 10:36

import apps.main.models.work_model
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text='The name of the category.', max_length=100, verbose_name='Name')),
                ('active', models.BooleanField(default=True, help_text='The active status of the category.', verbose_name='Active')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The image of the gallery.', upload_to=apps.main.models.work_model.GalleryImage.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(help_text='The title of the work.', max_length=200, verbose_name='Title')),
                ('description', models.TextField(help_text='The description of the work.', verbose_name='Description')),
                ('image', models.ImageField(help_text='The image of the work.', upload_to=apps.main.models.work_model.Work.upload_to, verbose_name='Image')),
                ('category', models.CharField(help_text='The category of the work.', max_length=100, verbose_name='Category')),
                ('client', models.CharField(blank=True, help_text='The client of the work.', max_length=200, null=True, verbose_name='Client')),
                ('start_date', models.DateField(blank=True, help_text='The start date of the work.', null=True, verbose_name='Start Date')),
                ('designer', models.CharField(blank=True, help_text='The designer of the work.', max_length=200, null=True, verbose_name='Designer')),
                ('project_description', models.TextField(blank=True, help_text='The project description of the work.', null=True, verbose_name='Project Description')),
                ('story', models.TextField(blank=True, help_text='The story of the work.', null=True, verbose_name='Story')),
                ('approach', models.TextField(blank=True, help_text='The approach of the work.', null=True, verbose_name='Approach')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The creation date of the work.', verbose_name='Created At')),
                ('gallery_images', models.ManyToManyField(blank=True, help_text='The gallery images of the work.', to='main.galleryimage', verbose_name='Gallery Images')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
