# Generated by Django 5.1 on 2024-08-08 10:38

import apps.main.models.work_model
import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-created'], 'verbose_name': 'Imagen de la galería', 'verbose_name_plural': 'Imágenes de la galería'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-created'], 'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
        migrations.RemoveField(
            model_name='work',
            name='created_at',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, help_text='El estado activo de la categoría.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='El nombre de la categoría.', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='La imagen de la galería.', upload_to=apps.main.models.work_model.GalleryImage.upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='work',
            name='approach',
            field=models.TextField(blank=True, help_text='El enfoque del trabajo.', null=True, verbose_name='Enfoque'),
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(help_text='La categoría del trabajo.', max_length=100, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='work',
            name='client',
            field=models.CharField(blank=True, help_text='El cliente del trabajo.', max_length=200, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(help_text='La descripción del trabajo.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='work',
            name='designer',
            field=models.CharField(blank=True, help_text='El diseñador del trabajo.', max_length=200, null=True, verbose_name='Diseñador'),
        ),
        migrations.AlterField(
            model_name='work',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, help_text='Las imágenes de la galería del trabajo.', to='main.galleryimage', verbose_name='Imágenes de la galería'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(help_text='La imagen del trabajo.', upload_to=apps.main.models.work_model.Work.upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='work',
            name='project_description',
            field=models.TextField(blank=True, help_text='La descripción del proyecto del trabajo.', null=True, verbose_name='Descripción del proyecto'),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_date',
            field=models.DateField(blank=True, help_text='La fecha de inicio del trabajo.', null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='work',
            name='story',
            field=models.TextField(blank=True, help_text='La historia del trabajo.', null=True, verbose_name='Historia'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(help_text='El título del trabajo.', max_length=200, verbose_name='Título'),
        ),
    ]
