# Generated by Django 5.1 on 2024-08-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='category',
        ),
    ]
