# Generated by Django 5.1 on 2024-08-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_work_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='categories',
            field=models.ManyToManyField(help_text='Las categorías del trabajo.', to='main.category', verbose_name='Categorías'),
        ),
    ]
