# Generated by Django 5.1 on 2024-08-08 10:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_work_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='approach',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='El enfoque del trabajo.', null=True, verbose_name='Enfoque'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='La descripción del trabajo.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='work',
            name='project_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='La descripción del proyecto del trabajo.', null=True, verbose_name='Descripción del proyecto'),
        ),
        migrations.AlterField(
            model_name='work',
            name='story',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='La historia del trabajo.', null=True, verbose_name='Historia'),
        ),
    ]
