# Generated by Django 5.1 on 2024-08-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_work_approach_alter_work_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='website',
            field=models.URLField(blank=True, help_text='El sitio web del trabajo.', null=True, verbose_name='Sitio web'),
        ),
    ]
